name: 'Readme Auto Generator'
on:
  push:
    branches:
      - main
    paths:
      - 'readme.txt'
jobs:
  run:
    runs-on: ubuntu-latest
    name: Generate Readme
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Execute the markdown Readme generation script
      run: bin/generate-markdown-readme

    - name: Commit readme file
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply readme.md Changes
        branch: main
        file_pattern: readme.md